#!/bin/sh

PATH=./node_modules/.bin:$PATH

magick=magick

if ! command -v magick --version >/dev/null 2>&1; then
  magick=convert
fi

clean() {
  git clean -X
}

build_site() {
  mkdir -p dist
  node src/index.js
}

build_assets() {
  mkdir -p dist
  cp -a node_modules/dicecube/dicecube.js src/script/
  cp -a \
    src/script/* src/static/* src/static/.* \
    media/profile.webp media/pronunciation.mp3 media/og.jpg media/clip \
    dist
}

build_favicons() {
  $magick media/favicon.png -filter point -resize 50% dist/favicon-16x16.png
  $magick media/favicon.png -filter point -resize 100% dist/favicon-32x32.png
  $magick media/favicon.png -filter point -resize 200% dist/favicon-64x64.png
  $magick media/favicon.png -filter point -resize 562.5% dist/favicon-180x180.png
  $magick media/favicon.png -filter point -resize 600% dist/favicon-192x192.png
  $magick media/favicon.png -filter point -resize 1600% dist/favicon-512x512.png

  $magick dist/favicon-16x16.png dist/favicon-32x32.png dist/favicon.ico
}

build_sprite() {
  mkdir -p dist/i
  $magick -background black \
    media/sprite/phalanx.jpg \
    media/sprite/today.jpg \
    media/sprite/transactions.jpg \
    media/sprite/containers.jpg \
    media/sprite/dicecube.jpg \
    media/sprite/bf.jpg \
    media/sprite/reno.jpg \
    media/sprite/pomodoro.jpg \
    media/sprite/speed.jpg \
    media/sprite/eekwhales.jpg \
    media/sprite/climodules.jpg \
    media/sprite/stepanek.jpg \
    +append \
    dist/i/sprite.jpg
}

build_images() {
  for img in media/images/*.jpg; do
    for size in 1600 1200 600; do
      mkdir -p dist/i/"$size"
      $magick "$img" -resize "${size}x${size}>" +profile "*" \
        dist/i/"$size"/"${img##*/}"
    done
  done
}

build() {
  build_site
  build_assets
  build_favicons
  build_sprite
  build_images
}

# NOTE: This self-signed SSL certificate is NOT for production.
generate_ssl_cert() {
  mkdir -p dist
  openssl req \
    -newkey rsa:2048 \
    -new \
    -nodes \
    -x509 \
    -days 3650 \
    -keyout key.pem \
    -out cert.pem \
    -subj "/C=US/ST=Michigan/L=Detroit/O=Company Name/OU=Org/CN=localhost"
}

dev() {
  generate_ssl_cert
  serve -p "${1:-3000}" \
    --ssl-cert dist/cert.pem \
    --ssl-key dist/key.pem \
    --no-clipboard \
    dist
}

help() {
  echo "$0 <task> <args>"
  echo "Tasks:"
  sed -n 's/^\([a-z][a-z_]\+\)() {/\1/p' "$0" | cat -n
}

"${@:-help}"
